#!/bin/sh


javac *.java

echo
echo "*************************************"
echo "*************************************"
echo

echo "java KnapsackBU 17 50 ./tests/w.txt ./tests/v.txt 1"
java KnapsackBU 17 50 ./tests/w.txt ./tests/v.txt 1

echo

echo "java KnapsackTD 17 50 ./tests/w.txt ./tests/v.txt 1"
java KnapsackTD 17 50 ./tests/w.txt ./tests/v.txt 1

